
quarkus.langchain4j.timeout=120s
quarkus.langchain4j.ollama.chat-model.model-name=nemotron-3-nano:30b-cloud
quarkus.langchain4j.ollama.chat-model.temperature=0
langchain4j-ollama-dev-service.ollama.host=127.0.0.1
langchain4j-ollama-dev-service.ollama.port=11434
langchain4j-ollama-dev-service.ollama.endpoint=http://${langchain4j-ollama-dev-service.ollama.host}:${langchain4j-ollama-dev-service.ollama.port}